### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by eiabea** [Suor/pg-bricks#12]
I am trying to connect my node application (docker container) with a postgres instance (docker container) but getting

```
    error: password authentication failed for user "hades"
        at Connection.parseE (/src/node_modules/pg/lib/connection.js:539:11)
        at Connection.parseMessage (/src/node_modules/pg/lib/connection.js:366:17)
        at Socket.<anonymous> (/src/node_modules/pg/lib/connection.js:105:22)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:177:18)
        at Socket.Readable.push (_stream_readable.js:135:10)
        at TCP.onread (net.js:542:20)
```

The weird thing is, that i can connect to the database from each container, so if i try to run:

```
psql postgres://hades:hades@postgres:5432/hades
```
on either the postgres or the node container i can login to the DB, it only fails in the node application

pg_hba.conf
```
host all all 0.0.0.0/0 md5
```

it also works in the node application if i replace "md5" with "password", but that is not the standard behaviour of the postgres image, so i think it has something to do with pg-bricks or pg (i also tried to connect with the bare pg node module which also fails)

pg-bricks version: 0.4.0
postgres version: 9.4, 9.5.3

**Comment by eiabea** [comment]
Sorry for the issue!

```
rm -rf node_modules; npm install
```

fixed the problem...
